### ISSUE TITLE
Set Up Permenent SMTP Service for Discourse

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint.github.io#11]
Right now, our in develop Discourse forum is using gmail smtp service under my account so I can configure the site to our needs. It has a 99emails/day limit which can be frustrating to work with. 

As it currently stands we only need email for account verification and notifications, everything else that requires email is optional. So we could get away with using the free tiers of [Mailgun](http://mailgun.com) or another service. The downside is that I personally do not own the mypaint.{org, info} domains so I can't set the accounts up. So I would need @jonnor and @achadwick to coordinate with me with creating the account for SMTP and adjusting the DNS records to reflect this. Mailgun has an easy step by step process on how to do this.

**Comment by odysseywestra** [comment]
Okay I have Mailgun set to use the no-reply.mypaint.org subdomain. In order for it to work, I need @achadwick  to set the following DNS records. 

1. Add DNS records for sending

Type | Hostname | Value 
------------ | ------------- | -------------
TXT | no-reply.mypaint.org | v=spf1 include:mailgun.org ~all
TXT | smtp._domainkey.no-reply.mypaint.org | k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDEQsJPyw0ZUH5vY4DjGc+Zv1Iry6kH7wxmmm66XvLoJOcSZAyCRCn/jnHVb65SUt7UVQGUeEmsZHUTiAG8rfKvzUISLLRxoiFKVJk8kSU5PwZYyAmJ+4E6sveyXoWjZK1SVuMP5hny1Pg1X03oGyZ8WrUZGEQHqo0S7MFJHneokwIDAQAB

2. Add DNS Records for Tracking

Type | Hostname | Value
------- | ---------- | ----------
CNAME | email.no-reply.mypaint.org | mailgun.org

The third step is optional since we are only using email for account verification and notifications. I might enable email digest, but I want to see how many emails we send over the month before enabling that feature. 

After Mailgun can verify the required DNS records, we can move on to move the discourse site to it's correct domain.

**Comment by achadwick** [comment]
@odysseywestra I've made those three changes, and they should be available in 5 minutes or so. I assumed the CNAME should be `mailgun.org.` with the trailing full stop, to prevent it resolving to `mailgun.org.mypaint.org`.

**Comment by odysseywestra** [comment]
Good ideas about preventing it from resolving to a subdomain is doesn’t need to be. According to Mailgun it looks good on my end with the exception of the MX records, but don't worry those are not required. I'll update the discourse docker container's `app.yml` file and redeploy the container.

**Comment by odysseywestra** [comment]
Alright, Discourse site is rebuilt and re-deployed. I sent myself and @achadwick a test email to see if it's functioning. I received the test email and looks good so far to me.

**Comment by achadwick** [comment]
I got an "Email Deliverability Test" from a `noreply@test.odysseywestra.com` which gmail identifies as "[via](https://support.google.com/mail/answer/1311182?hl=en-GB) no-reply.mypaint.org". I'll assume that'll change when we get the final domain in place though :)

**Comment by odysseywestra** [comment]
Yes it will. I think it's reflecting the url I gave in it's docker
container file.

**Comment by odysseywestra** [comment]
Okay well since Mailgun hasn't given me any problems. I think I can call this a permanent SMTP solution for now.
