### ISSUE TITLE
Category Tags for Discourse

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint.github.io#13]
Okay I was wondering what categories we should have for our discourse site? Dose anybody remember what categories we had with the old site? Here some ideas of Categories we could go with:

* Art Showcase
* Projects
* Tutorials
* Art Challenges
* Development Help

So what categories would you want on this forum?

**Comment by odysseywestra** [comment]
I added the categories to the discourse site and added their descriptions. If any categories come to mind, let me know down below.

**Comment by odysseywestra** [comment]
I've also added a Resources Category. I think we have all the categories we need for now. If anybody wants any more categories just open up an issue and well discuss it.

**Comment by achadwick** [comment]
There is a "Post Discussion" subcategory of "General Talk". I just tried to reassign an existing site post into it, and I can't - it's not offered as a category.

I like the categories. Maybe the "/c/devops" in the link should be "/c/development" though? I'm thinking it's going to be more about helping people get oriented with the code than day-to-day running.

**Comment by odysseywestra** [comment]
Actually it's doing just as designed. I need to add tl-03 to the list for those who can create though. I only want that place for blog posts. I also did added an announcement category for things happening specifically on the discourse server to

**Comment by odysseywestra** [comment]
Actually I can add you to the staff group instead.

**Comment by odysseywestra** [comment]
Nvm, I discourse won't allow me to do that. I'll have to make you moderator so you can create posts there. @deevad do you want me to make you a moderator as well?

**Comment by odysseywestra** [comment]
Also I've changed /c/devops >> /c/develoment. Sorry for all the comments. ^^'

**Comment by Deevad** [comment]
@odysseywestra (about moderation account ) No thanks for now, I'll try to be a user at first, and open a gallery of sketch.
