### ISSUE TITLE
Select Subdomain for Discorse Site

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint.github.io#14]
In #2 I mentioned about needing to select a subdomain for MyPaint.org discourse site. Here is a quote of a few suggestions from that issue.

>Lastly we need a subdomain for the community forums. Here's a list of some suggestions:
>forum.mypaint.org
>discuss.mypaint.org
>community.mypaint.org
>chat.mypaint.org
>discourse.mypaint.org

Me personally, I'm leaning towards either `discuss.mypaint.org or community.mypaint.org. Let me know also your guys subdomian ideas as well. As a side note, this will also have to reflect on mypaint.info as well.

**Comment by odysseywestra** [comment]
Once We get a subdomain selected, I can go ahead and configure our discourse social login functions. So we will be able to log in via Github, G+, Twitter, and Facebook.

**Comment by achadwick** [comment]
I think I like generic names that are independent of the specific board system being used. But it's not a hard preference, since we can always alias an old name to a new one.

Rough preference, first choice first:

1. forums.mypaint.org (or "forum" singular)
2. community.mypaint.org
3. discourse.mypaint.org

"discuss" clashes with the name of the existing mailing list, and it's really not a chat tool - you'd want something like gitter or irc or slack for that.

**Comment by odysseywestra** [comment]
That's true since we do have the mailing list. Funny thing is that if we can cover the costs of the SMTP relay. we could enable email create and reply in discourse and essentially replace the mailing list. However, I save that conversion for another day.

If we were left with those three choices, I would lean towards community.mypaint.org since technically it is a community. Plus for me it easier to type community than forums. ^^'

**Comment by achadwick** [comment]
I quite like "talk.mypaint.org" too. Nice and short!

But let's go with "community" if you don't like that ☺

**Comment by odysseywestra** [comment]
Yeah, I'm still leaning towards community.mypaint.org. It just seems to fit better and roll off the tongue despite being longer. ^^'

We can use both, But I would want the official one to be community.mypaint.org.

The IP address for the server is: http://162.243.216.182/

Okay once you adjust the DNS records, I'll rebuild and re-deply the discourse server. I also need to adjust some settings in it nginx server as welll.

**Comment by achadwick** [comment]
@odysseywestra Done! community.mypaint.org should be live now.

**Comment by odysseywestra** [comment]
Okay site is rebuilding should be up in a few minutes.

**Comment by odysseywestra** [comment]
Okay I had to rebuild it a couple of times, but our Discourse Site is now live at http://community.mypaint.org.

@achadwick Could you announce it on  Twitter?
