### ISSUE TITLE
Make sure Discourse is Compatible to our Code of Conduct and Licensing policy

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint.github.io#16]
Just want to make sure that our Discourse Site's FAQ, TOS, and Privacy Policy Conforms to our Code of Conduct and Licensing Policy. If not, we need to edit accordingly.

* [MyPaint community forum Community Guidelines](http://community.mypaint.org/faq)
* [MyPaint community forum TOS](http://community.mypaint.org/tos)
* [MyPaint community forum privacy policy](http://community.mypaint.org/privacy)

**Comment by odysseywestra** [comment]
I've started a Discussion Thread about this Issue over on our Community Forums as Well.

http://community.mypaint.org/t/make-sure-discourse-is-compatible-to-our-code-of-conduct-and-licensing-policy/67

**Comment by achadwick** [comment]
I've taken the liberty of updating the links.

**Comment by achadwick** [comment]
I'm not sure we need two open discussion threads about one issue.

The MyPaint Contributor Code of Conduct is mostly compatible with the forums' Community Guidelines, I think. The CGs emphasize politeness and point at the TOS for teeth. The TOS gives us some useful post removal teeth and the scope to act at our discretion when upholding the CG or the CCoC. The CCoC just straight-up forbids certain behaviours, and (should) provide an email address for reporting, but there's nothing precluding the CGs "flag it and move on" approach, that's fine too and seems a reasonable way to report many things.

We will need to upgrade the Contributor CoC to a more recent version shortly anyway (1.3, with its clearer reporting pathways for serious violations). 1.3 is very likely to be mostly compatible too.

The CG very much needs to provide an extra para in its Terms of Service heading stating:

> Please note that contributors to the MyPaint project govern themselves by a [Contributor Code of Conduct](https://github.com/mypaint/mypaint/blob/master/CODE_OF_CONDUCT.md). By participating in this project, you agree to abide by its terms.

Do we need to reproduce any bullet points too?

----------------

For the avoidance of doubt, we need to decide whether the MyPaint community forums are a project space, or a public space. To me it sure looks like a project space, with all those Developer Area bits.

Therefore I do not think the forum NSFW category is wise to have initially, as it may encourage postings which are in conflict with the CCoC or which exist in a grey area. Perhaps the category should be dropped until we have a better idea of what's going on and how such a category should be managed?

-------------

The TOS needs the following global search and replaces:

* `company_domain` → community.mypaint.org
* `company_full_name` →the MyPaint Development Team and its designated Community Managers
* `company_short_name` →the MyPaint Community team

(Does that fit with your idea of who runs the forums? "[The] MyPaint Development Team" is becoming the umbrella term for us lot, I feel, and I'm OK with that.)

**Comment by odysseywestra** [comment]
> I'm not sure we need two open discussion threads about one issue.

I did this to widen the scope of discussion. This allows people who do not feel the need to have a GitHub account, but still want to precipitate(Hence the Discussion Label) in community feedback. Once the issue is closed the thread on that side is closed as well. I'm testing this out with the MyPaint.Org issue tracker. If it seems effective, and I have the moderators who are willing to help out, I'll propose we give expand the MyPaint and Brush Engine Issue Trackers. Don't worry I have a long term plan for this.

>We will need to upgrade the Contributor CoC to a more recent version shortly anyway (1.3, with its clearer reporting pathways for serious violations). 1.3 is very likely to be mostly compatible too.

>The CG very much needs to provide an extra para in its Terms of Service heading stating:

> "Please note that contributors to the MyPaint project govern themselves by a Contributor Code of Conduct. By participating in this project, you agree to abide by its terms."

>Do we need to reproduce any bullet points too?

Yeah I would add that extra para in the Community's TOS. Plus I would also mention the TOS in our Code of Conduct as well.

>For the avoidance of doubt, we need to decide whether the MyPaint community forums are a project space, or a public space. To me it sure looks like a project space, with all those Developer Area bits.

>Therefore I do not think the forum NSFW category is wise to have initially, as it may encourage postings which are in conflict with the CCoC or which exist in a grey area. Perhaps the category should be dropped until we have a better idea of what's going on and how such a category should be managed?

Right now it can be considered both. The reason I made those categories was to help the Issue tracker stay focused, on bugs and Issues, and the Developer Area's Categories be user/developer help. And the GitHub Issue category is only for issues we need further feedback on (only Admin and TL_03 can create posts there). With that said I still want this to be a place where an artist can showcase their work, tutorials, resource, ect. so we can connect to each other. Basically bridging the gap between developers and it artist and users.

WIth that in mind, the NSFW is locked down to only those with TL_02 can post there, even then you have to be logged in to see the content. Plus the category can be muted if the user dose not wish to be notified of posts there. Also I did recently set it so that all new users are muted to this category thus making the NSFW category an opt-in instead of a opt-out option. 

Also keep in mind that the Server is in New York, so I also have to keep in mind US Laws as well.

> The TOS needs the following global search and replaces:

>     company_domain → community.mypaint.org
>     company_full_name →the MyPaint Development Team and its designated Community Managers
>     company_short_name →the MyPaint Community team

> (Does that fit with your idea of who runs the forums? "[The] MyPaint Development Team" is becoming the umbrella term for us lot, I feel, and I'm OK with that.)

Yes, (The) MyPaint Development Team feels okay for me as well.

**Comment by achadwick** [comment]
The TOS specifies that all postings are made available under a Creative Commons By-NC-SA 3.0 license. This should be bumped to version 4.0.

We should also make it clear that this is an additional license which the poster grants to us and people downloading the content from the site, and that recipients may choose which license they use or redistribute the content under for no fee. This is standard [dual licensing](https://en.wikipedia.org/wiki/Multi-licensing). The poster must, obviously, be in a position where they can legally redistribute the content under the license they received it under, AND relicense it.

(I think that's the intent of the TOS clause)

-----------------------------

I suggest we strike out TOS section 10 ("Advertisements"), or replace it with the following text:

> company_short_name reserves the right to display advertisements alongside your content unless you have purchased an Ad-free Upgrade or a Services account.

If we were to place advertisements in user content, we would violate both the NC and ND terms of the user content license.

**Comment by odysseywestra** [comment]
I will probably make that reflect our Licensing Policy, but let them know the it's only for the copy they post on the site. Plus advice them to watermark their to make this distinction. If they Link the work it retains the licensing of the source file.

I will remove that the advertising clause you mentioned

Okay with those comments I will post my revision here as a comment and if there are no objections, I will update them on our community site.

**Comment by achadwick** [comment]
Apologies for the slight false dichotomy earlier! Private spaces exist too, and the CCoC rightly does not concern itself with them.

The NSFW category is not a completely private space. It resides on forums which contain public/project spaces, all mixed in, so it can't really be dis-associated from them even if it's opt-in. I notice it in lists at the very easily granted "regular" trust level, albeit with a workable definition of what it's for and a "no porn" stipulation in the description.

The spirit of the CCoC is to avoid creating an environment that turns away new contributors by making it clear that harassing behaviour will not be tolerated. Pervasive sexualized imagery is oppressive for loads of people, and tolerating it anywhere could be taken as an indicator that we'd be OK with coddling harassing behaviour too. It's also irrelevant within project spaces, where we try to be professional.

For me, there's three ways forward:

1. Interpret every category as a project space, run by "the MyPaint Development Team and its designated Community Managers". Remove the NSFW category.
2. Interpret every category as a project space, run by "the MyPaint Development Team and its designated Community Managers". Forbid heavily sexualized nudity in the NSFW category, but permit non-sexualized artistic nudity.
3. Interpret every category as a public space, run by "the MyPaint Community Team" or similar. Keep the existing rules for "NSFW". Make it clear that the CCoC rules on imagery would be interpreted more laxly there when they're applicable. Make it clearer still that other potential harassment of any sort will not be tolerated.

I don't like to compromise here, so I really favour "1" still. "2" works for me with a diverse enough crowd of community managers / moderators.

I think the goal of building bridges can still be achieved without compromising our existing undertakings under the code of conduct.

**Comment by odysseywestra** [comment]
I completely understand. Personally I agree with you on those views, but I also need to have a broader perspective and look at all points from the user. On the other end of the coin, blocking NSFW images can also be seen as oppressive, cause they'll see it as blocking a user to creatively express themselves even if it is not "normal" by society's standards. The same goes with excessively gore and violent content.

You are right, the NSFW category is not a completely private space and you can't really be dis-associated from it. It's really up to the user to not go there. I would really like to go with option one, but we would have to go with option two because we need to be open to all people without discrimination even if we are a project space. Now we can not allow heavily sexualized nudity(pornography) or images depicting  harassments of groups people since those do violate our CCoC. Artist Nudity, and depiction of gore and violence(as long as they are not harassing) do not violate out CCoC. 

Now I did state in "NSFW" category that we will not use them in our website(that includes the gallery), nor would we distribute them with MyPaint. I will also express that in our TOS and CG. I can also state that we will not host the images on the site, they can only be linked. That way they can have conversation about their work, and not be discriminated from posting as well since they also use MyPaint.

I highly doubt that the majority of our users(that includes me) will post on that category, but we still need to give them the choice to post there. In order to post, you have to be at Trust Level 2 or higher, but anyone can reply to that work posted so there is also that restriction as well.

**Comment by odysseywestra** [comment]
I did post about a reply on our Community Forums as well to see if anybody beside you or me who can weigh in on this. I'll post a comment here if there is a reply. to that thread.

**Comment by odysseywestra** [comment]
Okay I've finished the first draft of the [TOS for the MyPaint Community](https://gist.github.com/odysseywestra/3e08aabced847e631c5e). I paste it as a Gist to keep this comment short.

Here's what I did: 

[Section 2]
Added that content dose not violate our CCoC.

[Section 3]
Revised to use Creative Commons 4.0, plus put a limit clause in case user dose not wish to have content under said license.

[Section 10]
Replaced Advertisements with Distribution Rights. I will probably need help keeping the logic flowing correctly.

[Section 18]
Had to switch to New York Jurisdiction since our server is in New York State, USA. If anybody is has legal experience, please let me know if I missed something.

Please let me know of your guys thoughts about this TOS.  After we are done with this, I'll work on the Privacy Policy as well.

**Comment by odysseywestra** [comment]
Okay I've made a second edit to our TOS. Here what I did:

Section 3: User Content Liscense
I've moved a clause to the end of a sentence and made it a condition as well for content not license under our default license.

Section 10: Distribution Rights
I've added the sentence about us reserving the right to not distribute said content even if they do meet the requirements.

I've also correct misspelled words and made some grammar edits.

**Comment by odysseywestra** [comment]
I've posted the TOS on the community.mypaint.org so that we have a valid TOS. If you have any edits I need to make let me know.

**Comment by odysseywestra** [comment]
I did update our privacy policy. The only change I had to make was state that the server of the site is in the USA.

**Comment by odysseywestra** [comment]
Lastly I updated our Community Guidelines. The two changes I made were the statement that the MyPaint Community take harassment very seriously and reference our Code of Conduct. I've also added a section about showcasing artwork on the Community Site and what license the site it's under.

If anybody has comments about these TOS, Privacy Policy, or Community Guidelines please let me know and I will look into it.

**Comment by achadwick** [comment]
Speedy correction on section 3. ("User Content License") please

> (i) This Creative Commons License dose not apply on user contributions which have (i) already have a license posted on the content they own

Drop this clause. The UCL must apply on all postings regardless of whether the user chooses to apply another license, otherwise we have no right to distribute.

**Comment by achadwick** [comment]
(The UCL grant is *how* we obtain the right to distribute what people post)

**Comment by achadwick** [comment]
Little typo in <http://community.mypaint.org/faq#be-civil>

> \[...] the MyPaint Community team dose take harassment very seriously \[...]

→ "the MyPaint Community team takes harassment very seriously" maybe?

**Comment by achadwick** [comment]
Speedy correction in http://community.mypaint.org/faq#artwork please:

> So if you do not wish to have your artwork under this license, you can either duel license your work and allow us to use a low quality version of your artwork, or use a stricter license and paste it in your post, or just simply link to it's source instead. If you choose to go with the later two, we the MyPaint Community team can not use the artwork on our website, or distribute it with MyPaint itself.

→ "If you don't want to release your artwork under this license, you can either post a low quality version of your artwork under it, or link to its source, or both. Discourse will automatically do both for sites it knows about when you paste a simple link. If you choose one of these approaches, the MyPaint Community team cannot use the artwork on our website, or distribute it with MyPaint itself."

Posters should straight up not be allowed to override the posting UCL, or we'll end up in a huge mess. We need it to apply so that we *can* redistribute posted content on the site, and it's a good idea to standardize so that we receive the same license for redistribution for all posting.

**Comment by achadwick** [comment]
Finally (\*wow\*!) thanks for looking into all of this in detail @odysseywestra, and sorry for not being clearer on the UCL bits earlier. You're doing sterling work here even just digging into all of this stuff! :cake:

**Comment by odysseywestra** [comment]
Okay I've did the edits you suggested, and understood the logic behind them. Except this one I have a question on. I think it needs to be worded better.

>"If you don't want to release your artwork under this license, you can either post a low quality version of your artwork under it, or link to its source, or both. Discourse will automatically do both for sites it knows about when you paste a simple link. If you choose one of these approaches, the MyPaint Community team cannot use the artwork on our website, or distribute it with MyPaint itself."

"If you don't want to release your artwork under this license, you can either post a low quality version of your artwork under it, or link to its source, or both. Discourse will automatically generate a summary for sites it knows about when you paste a simple link. If you choose to only link your artwork on your post, the MyPaint Community team cannot use the artwork on our website, or distribute it with MyPaint itself."

We can redistribute the lower quality image if they decide to upload that instead. We can't redistribute link artwork cause they are on a third party site outside of Website.

**Comment by odysseywestra** [comment]
Okay I've posted over at mypaint/mypaint#528 that we should just make our UCL policy to only the original poster my republish contributions. 

> There is also the option of just have the policy of  [only the original poster may republish contributions](https://meta.discourse.org/t/who-owns-the-content-you-post-on-a-forum-aka-user-content-licensing/4261/3?u=odysseywestra) Since the majority of our users will be artists they may opt for this. That way we can just leave the licensing policy(with exception of updating to the CCv4) the way it is and just tell if they want their artwork on our website or distributed with MyPaint, they would just need to license their content on our forums as CC-BY or CC-BY-SA. 

>A good example of this is the forum for the [KDE Forms](https://forum.kde.org) where the [Krita Community Resides](https://forum.kde.org/viewforum.php?f=136) Their policy clearly states that 
> >"All messages belong to their poster and they have the full responsibility for any violation upcoming as a result of their post."
https://forum.kde.org/policy.php#policy4a

> I can see this in the long run would be the less headache route than trying to force a user or artist to use a certain license whether it's the Creative Commons or the GPL.

> I'm actually in favour with going this route.

And I also pulled another example from Deviantart's TOS as well.

> Deviantart also has a good section about Copyright in its TOS as well.

> > DeviantArt is, unless otherwise stated, the owner of all copyright and data rights in the Service and its contents. Individuals who have posted works to DeviantArt are either the copyright owners of the component parts of that work or are posting the work under license from a copyright owner or his or her agent or otherwise as permitted by law. You may not reproduce, distribute, publicly display or perform, or prepare derivative works based on any of the Content including any such works without the express, written consent of DeviantArt or the appropriate owner of copyright in such works. DeviantArt does not claim ownership rights in your works or other materials posted by you to DeviantArt (Your Content). You agree not to distribute any part of the Service other than Your Content in any medium other than as permitted in these Terms of Service or by use of functions on the Service provided by us. You agree not to alter or modify any part of the Service unless expressly permitted to do so by us or by use of functions on the Service provided by us.

Like stated in the quote I would also go this route.

**Comment by odysseywestra** [comment]
I should also create an human readable version of our TOS so that people have a general idea of what our TOS covers.

**Comment by odysseywestra** [comment]
Okay I've updated the [Draft TOS](https://gist.github.com/odysseywestra/3e08aabced847e631c5e) to reflect my proposed idea above. Here are the Changes:

[#3]: The Contributed Content belongs to the content contributor. Grants the forums and it user to be able to use such content within the forum and share it through media channels. Plus added that we may retain content if they are deleted for a certain amount of time.

[#4]: Moved the Distribution paragraph to position 4. Deleted  paragraph about payment and renewal; plus the paragraph about services. If we with to provide those in the future, we can put those in.

Let me know your thoughts to see if this would be the better route.

**Comment by odysseywestra** [comment]
Okay I've added a Human Readable Version to the [Draft TOS](https://gist.github.com/odysseywestra/3e08aabced847e631c5e). It still too long for my liking, so any suggestions on how to shorten this will be awesome.

**Comment by achadwick** [comment]
Simplifying and clarifying "4. Distribution" a bit more :smile: 

> The MyPaint Community team <ins>and others</ins> may <ins>re</ins>distribute user contributions with the MyPaint team's open source software, its website, and <del>its Community Forums</del> <ins>on third party websites and media,</ins> <del>as long as (i) the content has</del> <ins>but only if you explicitly grant additional Creative Commons</ins> licensing <ins>to all parties</ins> that abides by the MyPaint <del>Community team's</del> Licensing Policy<ins>.</ins><del>, (ii) and the MyPaint's Community team abides by the terms and conditions of the license whether it is the license described under the User Content License, or the license that provided with the content.</del> <ins>By doing so, you acknowledge as the copyright holder that all parties receiving your content under both licenses may use and redistribute it under the terms of whichever of the two licenses they choose, and only that chosen license.</ins> The MyPaint Community team <del>also</del> reserves the right to not <ins>re</ins>distribute user contributions even if the content meets the above requirements.

Or for cut and paste:

> The MyPaint Community team and others may redistribute user contributions with the MyPaint team's open source software, its website, and on third party websites and media, but only if you explicitly grant additional Creative Commons licensing to all parties that abides by the MyPaint Licensing Policy. By doing so, you acknowledge as the copyright holder that all parties receiving your content under both licenses may use and redistribute it under the terms of whichever of the two licenses they choose, and only that license. The MyPaint Community team reserves the right to not redistribute user contributions even if the content meets the above requirements.

I think the wording is a bit backhanded still ("hey, we can do this! but actually we can't unless you say we can!"). What do you think? Reverse the sense?

We do need to say "as the copyright holder" I think: the choice to grant extra licensing and downstream choice of license can only be exercised by the copyright holder.

**Comment by achadwick** [comment]
The little changes I've suggested above leave UCL license requirements to the forum TOS, and promo license choice to the MyPaint Licensing Policy as much as we can. I'm trying to carry on what I think is the separation of concerns you're aiming for :smile: 

I'd really rather we stick with CC BY-SA-NC 4.0 because it's clear and widely understood, but $STANDARD_BOILERPLATE would be technically OK too if users demand it.

What I mean by that is: have artists insisted on reserving all rights except our (and only our) ability to run a forums site featuring their work? I don't really see any feedback anywhere to that effect.

(You have more expertise with the artist community, so your opinion probably overrides mine!)

I'm from geekdom and the free software internets. I'd prefer CC licenses by default, just like upstream Discourse. I'm cool about NC clauses for the UCL provided it's clear how to waive them (for everyone, not the CC+ model). We shouldn't use ND clauses because remixing within the forums would be a pretty cool and creative outlet for users. More prosaically, people will need to be able to quote and modify text when they reply.

Creative Commons licenses have the advantage of being *much* clearer than standard TOS boilerplate, and they're quite well known. I can see why artists would want to be more restrictive, but I think commercial and copyright concerns should be covered by appropriate choice of CC modules for the UCL. That leaves moral rights, which are retained by a CC license but agreed not to be exercised :neutral_face: 

It's your call, and avoiding management headaches is totally a worthy goal too. Above is just my free software geek's opinion.

**Comment by odysseywestra** [comment]
I understand. Luckily, I was exposed to the open source world at the same time I became interested in doing artwork, so I understand the open source culture. For some people(especially artists), copyright is important to them cause it something they created, and by nature they want to protect it. With that said most artist will see that MyPaint is free as in beer, but not realize the open source culture behind. So having a forum that respects their rights as an artist is a plus for them, and it also gives us the opportunity to be expose them to the Open Source world and see that there is more to the Software than its UI. 

You can also look at it this way. Their work made by MyPaint is still being exposed to the world, but in newspaper terms, it would be considered the classifieds. So in order to get to the front page(our website), they would have to follow certain terms(Like our Licensing Policy) to get exposure to a more broader audience. Shifting back to reality, by then, they'll understand the open source nature of the Creative Commons, the GPL, the MIT, etc, cause they would have to do the research to understand our Licensing Policy. If they don't then they would be considered foolish.

So in the long I don't think we will regret this. And if we do regret this decision, it just requires changing the TOS, but we will have to deal with the fallout for that change. Going this route is the best way to go so I'm going to go ahead and apply it our Community Forums. If we need to make any more changes to our TOS, just open up a new issue thread.

**Comment by odysseywestra** [comment]
Okay I’ve pushed the changes of our TOS to our Community Forums. I've also changed our FAQ to reflect the changes as well.
