### ISSUE TITLE
Using Discourse as our Comment System For Blog Post

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint.github.io#17]
It would probably be nice to embed Discourse as our Comment system for our blog. The biggest plus side would that we wouldn't have to manually create a new comment thread on our discourse site like we are doing now. The other plus side, is that since Jekyll uses templates and layouts to generate the static site, all we need to do is add Javascript layout a `comments.html` in the `_includes` folder and add it to the `post.html` in the `_layouts` folder. That way Jekyll with automatically add the js snippet on each new post. Lastly it will further strengthen us encouraging to using our forums which would be nice. 

The downside however, is that well have to use Javascript. I would like to use a little js as possible, to avoid site overhead, but the pros do out weight the cons in this situation. So what are your guys thoughts? Should we implement this? Are there alternative ways to implement this with out using Javascript.

[Example thread of how it would look](http://eviltrout.com/2014/01/04/hiding-offscreen-ember.html)
[How to Embed it](https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963)
[Example of how one implemented it on Github Pages](https://meta.discourse.org/t/trouble-embedding-discourse-as-a-comment-engine-using-github-pages-and-digitalocean/17520)

**Comment by odysseywestra** [comment]
Okay I've enabled Discourse Comments on our Website. There are still a couple of visual css fixes I need to add, but the basic functionality is there.

**Comment by odysseywestra** [comment]
Alright I've add my notes on how to manipulate the Discourse Comments here:

https://github.com/mypaint/mypaint.github.io/wiki/How-to-Submit-a-Post

I considered this as complete. Closing Issue.

**Comment by PackElend** [comment]
> [Example thread of how it would look](http://eviltrout.com/2014/01/04/hiding-offscreen-ember.html) [How to Embed it](https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963) [Example of how one implemented it on Github Pages](https://meta.discourse.org/t/trouble-embedding-discourse-as-a-comment-engine-using-github-pages-and-digitalocean/17520)
that is death end

> https://github.com/mypaint/mypaint.github.io/wiki/How-to-Submit-a-Post
that ends up creating a new wiki page

would you mind updating the links?
merci :)
