### ISSUE TITLE
DNS 'www' problem for Discourse Site

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint.github.io#18]
I've noticed that whenever I type `http://www.community.mypaint.org` I get an "Unknown Host Errror" when I ping it. However when I type `http://community.mypaint.org` I'm able to connect just fine. It doesn’t effect the base domain though. It's also effect the `community.mypaint.info` sub-domain as well.

Could you look into it @achadwick since you have admin access to the DNS settings of them?

**Comment by achadwick** [comment]
community.mypaint.info is just a host name, not a subdomain. Is this likely to be a problem?

I've added a `www.community` CNAME.
