### ISSUE TITLE
Enable OAuth2 Logins for Discourse

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint.github.io#19]
Currently we only have email login only for our [Community Forums Login](http://community.mypaint.org/login).

I would like to start with Github Login and Twitter Login, because those are the two places MyPaint currently has an account at.  

@achadwick I will need your help on this one since you have admin access for both accounts. I will need you to set up the applications and message me the credentials for both. I'll have links on how to do this below.

I would also like to do this for G+ and Facebook, but currently I can't get a hold of the person who manages both of them. Here are the Pages: [Facebook](https://www.facebook.com/Mypaint-105492632873394/), [Google +](https://plus.google.com/118198715229579146301).

[Configuring GitHub login for Discourse](https://meta.discourse.org/t/configuring-github-login-for-discourse/13745)
[Configuring Twitter login for Discourse](https://meta.discourse.org/t/configuring-twitter-login-for-discourse/13395)

**Comment by odysseywestra** [comment]
@achadwick have you made any progress on this? I would like to get the Github and Twitter OAuth2 logins enabled soon.

**Comment by achadwick** [comment]
I'm always nervous about turning on new apps in anything. Sorry for the delay! Twitter set up. I've used:

* Name ("Your application name. This is used to attribute the source of a tweet and in user-facing authorization screens. 32 characters max.): **MyPaint Community Forum**
* Description ("Your application description, which will be shown in user-facing authorization screens. Between 10 and 200 characters max."): **Meeting place, art showcase, and discussion board for artists and developers who work with the MyPaint art program.**

Hope that's OK. I'll email you the secrets shortly.

**Comment by odysseywestra** [comment]
Alright, I have Oauth2 Authentication for twitter enabled. However I just realized that it will not allow you to connect twitter account to your discourse account. So if you created an account prior to us enabling twitter login, you are basically out of luck. Huuu.... well that sucks. 

It due to the fact that twitter will not share their user's email address. I may have to keep it disabled till after twitter and discourse sort it out. Thoughts?

**Comment by achadwick** [comment]
Okay, GitHub next. Here's how I've configured the app:

* Application name ("Something users will recognize and trust"): **MyPaint Community Forum**
* Application description ("This is displayed to all potential users of your application"): **Meeting place, art showcase, and discussion board for artists and developers who work with the MyPaint art program.**

I'll email you the tokens shortly. Hopefully GitHub are a bit smarter about social login than Twitter.

**Comment by odysseywestra** [comment]
Alright Github login is enabled. Luckily with Github, as long as your email for each account matches, it will recognize you. Okay all that left is Google+ and Facebook, but at a later time.

**Comment by odysseywestra** [comment]
Closing since we have basic OAuth2 enabled. I will open up separate issues when it comes to enabling OAuth2 for Google+, and Facebook since it will require someone to maintain a page.
