### ISSUE TITLE
Setting up Community Forum

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint.github.io#2]
I'm in the process of getting a Discourse community forum on a Digital Ocean Droplet up and running. After a bit of asking around, someone is interested in sponsoring the server for us so that one weight off our shoulders if they take us on. I will probably expand issue tracker for website to also include the community forums as well it keep it focused.

So all in all I want to find out is what categories do we need for the site. Who would be willing to help me moderate it. And basically establish the grounds for the community site.

As far as URL subdomains are concerned, @achadwick suggest using the "forums" sub-domain, and I suggested the "community" sub-domain.

Okay let me know what your guy's thoughts about get this community forum set up.

LIST OF WHAT NEEDS TO BE DONE:

- [x] Choose subdomain to assign the discourse site.
- [x] Set Mailgun SMTP settings
- [ ] Customize header to match mypaint.org

**Comment by odysseywestra** [comment]
Okay, the person that said that was interested in sponsoring our community forums said they will have the server set up soon. So defiantly by the end of the week, the new community forums will be up.

If anybody is wondering the person sponsoring the server on Digital Ocean, it is Noah Chelliah who is the owner of [Altispeed](http://www.altispeed.com/) in Grand Fork ND, USA. He is also the co-host of Jupiter Broadcasting's the Linux Action Show. 

I'll have root access to the server, and I can also give root access to @achadwick if you want.

**Comment by odysseywestra** [comment]
Alright, I finally have a Debian Server hosted on Digital Ocean which is sponsored by Altispeed up. I'm currently setting up discourse in a docker container. @achadwick do you want me to create an user for you? That way you could make a backup of the docker image incase this happens again. I'll be doing the same as well.

The only thing holding the discourse server back is the smtp server for emailing. According to Send Grids policy, you have to be the owner of the domain being used. So whoever owns the http://mypaint.org domain, needs to create an account. They offer 12k emails/month for free after that it starts a $10/month for 40k emails/month. I don't think well go over 12k/month though. Once the account is created and cleared, I will need the SMTP credentials, then I can continue. We do not have to use sendgrid, but so far by my research, it is the best one for our use case.

Another option would be to great a Google Apps account and use their SMTP relay services. It costs around $5/month though. I would opt to use google's free smtp, but it's limited to 99emails/day. Plus someone already created a google account for MyPaint so we may need to track that person down. There is also yahoo, but like google it's limited to 500 emails/day, and mypaint is claimed...

Lastly we need a subdomain for the community forums. Here's a list of some suggestions:
forum.mypaint.org
discuss.mypaint.org
community.mypaint.org
chat.mypaint.org
discourse.mypaint.org

My goal is to get this server up and running this week so if you guys can help with these things that would be great.

**Comment by odysseywestra** [comment]
There is also Mailgun as alternative, which actually might be cheaper in the long run. Like SendGrid however, you have to own the domain which I don't.

**Comment by achadwick** [comment]
I don't want to be involved in the day-to-day running of a forum.

@odysseywestra What actual emails need to be sent? User account management only, or do users need to be able to post to the forums over email (ideally, we'd turn this off...)

Can we get away with an SMTP server listening on localhost only and capable of forwarding, with bounceback and admin `*@mypaint.org` addresses that can hit a redirector? Because we can do that already without extra outlay. I am already paying for web/email redirection <https://www.mythic-beasts.com/sales/hosting-other#redirect>, I just haven't set up any mail redirects yet :fearful: 

I don't own the `mypaint.org` domain, @jonnor does. However I do administer it. I'm the one responsible for the DNS hosting, and can adjust MX records.

**Comment by odysseywestra** [comment]
@achadwick That's understandable. I was just making sure I had a backup plan incase something where to happen to me, that no would be locked out like last time. If any collaborators, or core devs would like access to server just let me know.

Okay for now I'm using google's portable smtp server until we figure out what to do about smtp. It is limited to 99emails/day, and it will be under my email address. The plus side is that with [Docker](http://docker.com) it is very easy to switch to a different smtp mail server without breaking the site. Plus I'll be limiting a lot of email stuff so we when create an account with [SendGrid](http://sendgrid.com), [Mailgun](http://mailgun.com), or our own solution and not use a lot of resources. I'll make a separate issue about smtp to keep this thread focus.

So for this week, I'll be customizing using old assets form our website. Plus since it is sponsored by Altispeed, I'll be putting their logo at the footer of the website as a form of thank for taking us on. @achadwick I email you the domain where it's temporary at.

As far as DNS management, if you can give me admin access to the domains, I can do all that work. That you can focus still just focus on development work.

That should be it. So hopefully by next Monday, we will have a discourse server for mypaint.

**Comment by odysseywestra** [comment]
Right now the site is on invite only. So if anyone wishes to have access to the site for testing purposes and feedback, let me know.

**Comment by odysseywestra** [comment]
Okay I did set a due date for Discourse Site Launch Milestone to January 1, 2016. This is to help me and those that help to stay focused.

**Comment by odysseywestra** [comment]
Alight I turned back on user sign on for people to test it out before we launch it. Also if you been invited feel free to invite someone as well.

**Comment by odysseywestra** [comment]
I'm going to go ahead and close this since it basically set up. If you would like to add any features to our community forums just open up a new issue ticket.
