### ISSUE TITLE
PNG uploads are not supported

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint.github.io#20]
If I try to upload a PNG file, I get the message

> Sorry, the file you are trying to upload is not authorized (authorized extension: jpg, jpeg, gif).

Please could png be added to the list? Thanks.

**Comment by Nj27360** [comment]
I have this same problem too. Another thing I had problems with was using my Gravatar avatar on the forum. When I try to add it, I get the message "Sorry, but the avatar you have selected is not present on the server. Can you try uploading it again?", even after clicking the "Refresh your Gravatar" button. Can this be fixed please?

**Comment by odysseywestra** [comment]
Okay it was turned off because I wanted to conserve space. Since I configure the Nginx file size limit last time I rebuilt the container, I do not have a problem adding this back.

**Comment by odysseywestra** [comment]
@Nj27360 could you please open a separate issue about your gravatar? It is unrelated to the topic at hand. Thank you. ^^
