### ISSUE TITLE
Correction to TOS: 4. Distribution

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint.github.io#21]
Little correction for <http://community.mypaint.org/tos#4>. A key phrase seems to have drifted since <https://github.com/mypaint/mypaint.github.io/issues/16#issuecomment-164751933>

> [...] By doing so, you acknowledge as the copyright holder that all parties receiving your content under both licenses may use and redistribute it under the terms of whichever of the two licenses <del>you</del> <ins>they</ins> choose, and only that license. [...]

Downstream users get to choose in this dual model. Those downstream users would be... us, when it comes to asking for promo artwork. The clause is in there to allow promo use to be bound by only the CC license, without the Community forum's UCL being involved.

**Comment by odysseywestra** [comment]
Okay I pushed the change. Thanks for letting me know.^^

On Tue, Dec 15, 2015, 9:48 AM Andrew Chadwick <notifications@github.com>
wrote:

> Little correction for http://community.mypaint.org/tos#4. A key phrase
> seems to have drifted since #16 (comment)
> <https://github.com/mypaint/mypaint.github.io/issues/16#issuecomment-164751933>
>
> [...] By doing so, you acknowledge as the copyright holder that all
> parties receiving your content under both licenses may use and redistribute
> it under the terms of whichever of the two licenses you they choose, and
> only that license. [...]
>
> Downstream users get to choose in this dual model. Those downstream users
> would be... us, when it comes to asking for promo artwork. The clause is in
> there to allow promo use to be bound by only the CC license, without the
> Community forum's UCL being involved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mypaint/mypaint.github.io/issues/21>.
>
-- 

-- Albert Westra
