### ISSUE TITLE
“Discourse” or “Community’s Tools” forum

### ISSUE THREAD

**Issue by alexandre-mbm** [mypaint/mypaint.github.io#22]
_From:  [[Discourse] Hint: a category “Discourse” or “Community’s Tools”](http://community.mypaint.org/t/discourse-hint-a-category-discourse-or-communitys-tools/123)_

---

It would be a site for receive community newbies. Informal. GitHub Issues does not serve for this.

**Comment by odysseywestra** [comment]
After thinking about, I'm going to add a category called "Discourse Questions". Will that work?

**Comment by alexandre-mbm** [comment]
I think yes.
- [ ] Move my posts to there, please
