### ISSUE TITLE
community.mypaint.org: 500 Server Error

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint.github.io#28]
I'm getting 500 responses when I try to access any thread, or the discourse site itself. I've tried Chromium 49.0.2623.108, Firefox ESR 45.0.2, and a LWP-based command-line Perl client, and all of them return the same 500 error upon inspection:

```
$ GET -E https://community.mypaint.org/
GET https://community.mypaint.org/
User-Agent: lwp-request/6.15 libwww-perl/6.15

500 Internal Server Error
Connection: close
Date: Wed, 04 May 2016 09:05:29 GMT
Server: nginx
Content-Length: 0
Content-Type: text/html; charset=utf-8
Client-Date: Wed, 04 May 2016 09:05:28 GMT
Client-Peer: 162.243.216.182:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
Client-SSL-Cert-Subject: /CN=community.mypaint.org
Client-SSL-Cipher: ECDHE-RSA-AES128-GCM-SHA256
Client-SSL-Socket-Class: IO::Socket::SSL
X-Request-Id: 543de63c-ffba-4fe6-9c92-5c737e0da72d
X-Runtime: 0.085670

```

Chromium/Chrome gives the slightly confusing error page below, and shows a blue Reload button.

> The community.mypaint.org page isn’t working
> 
> community.mypaint.org is currently unable to handle this request.
> 500

Firefox just shows a blank page, but Inspector (Ctrl+Shift+I) shows the 500 in its Network tab when the page is reloaded.

**Comment by odysseywestra** [comment]
Seems to be the feature voting plugin causing the problem. After  I disabled it, I no longer get the error. Can you confirm it on your end?

**Comment by achadwick** [comment]
Yes, everything looks good for me now, as of 09:07 UTC.
