### ISSUE TITLE
community.mypaint.org: 502 Bad Gateway

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint.github.io#29]
Starting shortly after the [updates on 2016-05-27](https://twitter.com/MyPaintApp/status/735996800251764737), the site's nginx appears to have thrown a cog:

> 502 Bad Gateway
> 
> nginx

It's been just over an hour, so perhaps I'm reporting this too early :confused:

**Comment by odysseywestra** [comment]
The Upgrade process for discourse failed. Working on resolving it.

Here's the log:
https://gist.github.com/odysseywestra/0b8bcfab34543b99c4038fef734fea10

**Comment by achadwick** [comment]
I'm no expert, but it looks like some logdir-related redis issue. It's late here, there's a massive outage on my ISP's backhaul, and I've been fighting build breakages over a crappy phone connection. Sorry I can't be of much (any?) real help.

:sleeping: now

**Comment by odysseywestra** [comment]
Yup, you were right. One of the developers also said the same thing on the [Discourse Forums](https://meta.discourse.org/t/discourse-docker-image-version-1-3-3-released/44778/81?u=odysseywestra) as well. I had move a template in my app.yml in the right order

**Comment by odysseywestra** [comment]
I'm doing one more rebuild to see if the feature request voting is working again.

**Comment by odysseywestra** [comment]
Okay Community forums are back up and running.
