### ISSUE TITLE
Recover Lost Data from the Old Website

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint.github.io#3]
From @achadwick 

>Google cache to the rescue. http://mypaint.org/downloads/ is up (since it's what people have been looking for)
.-- from mypaint/mypaint#496

>I've reinstated a second pile of old posts, and dropped the placeholder since http://mypaint.org is now fairly reasonable as far as bare-bones info goes. Oh, and added a favicon ☺

>Please continue to dig around in Google caches and archive.is captures, and send PRs for missing pages. I have dumps of the posts' texts and will continue to reformat those into markdown-with-front-matter and put them in place.
--from #1 

So far we have posts dating back to Oct of 2010. That about half since the launch of mypaint in 2005 I believe. The strategy so has been looming around in google's cache and archive.is for previous posts and pages.

@achadwick is it possible you could do a past dump of what you have left as a gist. That way I can convert those to markdown while you focus on working on the main development work.

**Comment by tumagonx** [comment]
@odysseywestra in case you need any original mypaint for windows binaries before GI i still have it. For nostalgia reason.

**Comment by odysseywestra** [comment]
@tumagonx I believe all the windows builds you provided are on https://github.com/mypaint/mypaint/releases area. Though I would double check with @achadwick to make sure.

**Comment by tumagonx** [comment]
oops you're right!
how about an even older builds :) ?
mypaint 0.1 - 0.3, not  installers though and need preinstalled python 2.6 with pygtk

**Comment by achadwick** [comment]
@odysseywestra No problem, thanks for the offer.

https://gist.github.com/achadwick/78e50522b7a2f419771e

For the front matter in posts' Markdown, I've been using e.g.

```markdown
---
layout: post
title: "MyPaint 1.2.0-beta.3 released"
date: 2015-11-21 16:55:10
categories: blog
---

(... body here ...)
```

Categories just dictate how the permalinks present (unless overridden). There's sadly no way of making the old `/?p=<num>` permalinks work in Jekyll AFAICT.

**Comment by odysseywestra** [comment]
Okay I have taken what @achadwick gave me for posts and converted them to markdown. They are now committed as of 6d9549e and now online on at http://mypaint.org.

**Comment by achadwick** [comment]
Thanks for that, and for fixing up the links and the authorships☺

**Comment by odysseywestra** [comment]
Is there anything left we need to recover from the old site? 

Plus do we want to add all of @tumagonx builds to the Github release so they are at least archived?

**Comment by odysseywestra** [comment]
> Categories just dictate how the permalinks present (unless overridden). There's sadly no way of . making the old /?p=<num> permalinks work in Jekyll AFAICT.

@achadwick yeah it's a pain that we can't use the old permalinks, however we can create customize permalinks using the a keyword in the header of the markdown document.
```
---
permalink: /short-url/
---
```
That will at least make linking to each post or page much easier with shorter urls. Here's and example:

```
And here is the [link](/link-to-doc/) to the document you asked for
```

**Comment by odysseywestra** [comment]
I decided to roll back using permalinks on the site post. It ends up creating a local folder as well which will clutter up the generated website. I'll keep doing research about implementing permalinks though.

**Comment by odysseywestra** [comment]
Okay, just double checking. Is that any more content that we need to recover from the old site? If not, We can officially close this issue.

**Comment by odysseywestra** [comment]
Triage Note: If no one comments within a week of this post concerning anything we need to recover, I will consider this issue close.
