### ISSUE TITLE
community.mypaint.org cannot post 500 Internal Server Error

### ISSUE THREAD

**Issue by briend** [mypaint/mypaint.github.io#37]
500 Internal Server Error  when trying to reply or create a new topic.  Also chat box doesn't seem to work, just hangs.   This has been going on for several days.

**Comment by odysseywestra** [comment]
Okay, I did a container server rebuild and had to disable the chat box cause of issues with other forums. So could you post to make sure the error isn't popping up again? 

BTW, I'm thinking about instead starting a Telegram Group for MyPaint. Much easier to work with and supports bots.

**Comment by briend** [comment]
Thanks, that fixed it!  Telegram sounds interesting, but I don't have much experience with Slack, Discord, or any other team communication tools.  I'd be happy to test it with you though!
