### ISSUE TITLE
Create a Get Involve Page

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint.github.io#9]
Basically this is a landing page to not only link our soon to be discourse forums, but also social media sites such as G+, Facebook and Reddit. Plus a brief landing page for those who want to get involve with the development work of MyPaint, its website, and/or it forums. 

If anyone has a community site, or social page that related to mypaint, leave a comment down below and we'll see about adding it to the community page.

**Comment by achadwick** [comment]
Couple of ones I know about:

- http://made-with-mypaint.tumblr.com/
- http://mypaint.deviantart.com/

**Comment by achadwick** [comment]
Art communities and forums which relate to MyPaint can be listed on https://github.com/mypaint/mypaint/wiki/Community-and-Contacts too.

**Comment by odysseywestra** [comment]
So would you rather just have me link to that instead? I want to avoid duplicating work.

**Comment by achadwick** [comment]
Perhaps. I think we can use the wiki page as a collection ground for communities, and but present the ones we want to promote most on the site. I have a hunch that the forums are going to be a major element of MyPaint's community once they're up and running - Discourse is _nice!_

It's important to distinguish between official communities and social media stuff. Official: our polite and reasonable Discourse site. Unofficial: external tumblrs, deviantart, reddit, twitter hashtags. So perhaps that's two CTA buttons on a hypothetical participation page: one for Discourse, one linking to that wiki page? The blog and Twitter are sort of complementary announcement mechanisms, really.

I should probably sketch out a few ideas for you to shoot down as needed :)

**Comment by odysseywestra** [comment]
Okay I've created a [Get Involve](http://mypaint.org/involved) page which replaces the documentation page. Let me know what you guys thoughts and any edits I need to make.

**Comment by achadwick** [comment]
@odysseywestra I noticed that 69781ab1c29751571436dbd9494c579644612ad6 removed docs.md. Was that intentional?

**Comment by odysseywestra** [comment]
Yes it replaced it. Do you want me to add it back as direct link to wiki Documentation.?

**Comment by achadwick** [comment]
I've made a few changes, and fixed a few broken links and things. Let me know if I've missed any. I'll fix up the discourse site links when the configuration for the new final name is complete.

Thinking about design, I think those headings might (one day, when we have a consistent deaign) collapse to just a matrix of image links all of the same size. If we want to retain the text, we might use a rollover showing a block background image and the header for one state, adding the detail text in the other state.

Each little section might become a block that behaves like the diagram below, and which tiles together with other blocks.
![rollover](https://cloud.githubusercontent.com/assets/61299/11672217/6c158176-9e06-11e5-9571-3803c7de41bc.png)

Not to scale, and I don't know how workable it would be without doing it. For now, I'm trying to refine the texts to allow it by making them briefer and more equal in length.

**Comment by achadwick** [comment]
@odysseywestra Yes please. I think the link we need is https://github.com/mypaint/mypaint/wiki/Documentation (call it "Docs") in place of the FAQ link. That's how users should be getting to the manuals.

**Comment by achadwick** [comment]
(Still sticking my oar in, sorry to be a butt.)

I'm not sure I like the permalink `/involve/`, not sure why :neutral_face:
Would `/join/` be a better short form? Alternatively, `/engage/`? The page's job is to create engagement, I guess...

The link text (“Get Involved”) works for me though.

**Comment by odysseywestra** [comment]
As far as the Page it overall It looks great and flows nicely. Since the Discourse site is online at communtiy.mypaint.org, go ahead and change the URLs.

About the I did change it to `get-involve`, but the current commit changed it back. ^^' When you change the links for the Discourse Site, could you change that to? I'll leave the choice to whether you use `/join/` or `/engage/` or `/get-involve/`. 

Lastly I also added the link to the documentation in the header. Don't forget to do a git pull.
